### ISSUE TITLE
为何不用nodejs 做服务器，还要再装 java 和php?

### ISSUE THREAD

**Issue by longbai** [fis-dev/fis-qq-group#3]

**Comment by fouber** [comment]
@longbai 
1. 我们的java服务器实现起来成本更低，真正开发的 [代码](https://github.com/fouber/fis-command-server/blob/master/src/src/com/baidu/fis/HttpServer.java) 远比node的server更少。
2. fis的server支持连接php-cgi，这就大大扩宽了fis的本地调试支持范围，比如在百度，我们可以让工程师在本地直接把整个网站跑起来，而无需线上那种复杂的环境，这项功能大幅提升前端团队的开发效率。
3. nodejs服务器只能实现最基本的静态资源服务器功能，这个我们的server均能覆盖。如果用nodejs的server实现session、文件上传接收等功能的话，虽然有express也比较麻烦
4. 最新的fis并不要求装php，但java是必选的，这个要求比较低，用户环境很容易满足。
